Repository Paramdigma/Core, pull requests merged in 2020-06, with the labels that each got.

#13 Feature/GitHub actions CI
  .github/workflows/dotnet-core.yml
Labels: quality

#15 Added 2D delaunay and voronoi in Delaunay class.
  .gitignore
  src/Geometry/2D/Delaunay.cs
  src/Geometry/2D/DelaunayEdge.cs
  src/Geometry/2D/DelaunayPoint.cs
  src/Geometry/2D/DelaunayTriangle.cs
  tests/Geometry/2D/DelaunayTests.cs
Labels: enhancement

#6 Feature/primitives tests
  src/Curves/LevelSets.cs
  src/Geometry/3D/Line.cs
  src/Geometry/3D/Mesh/Mesh.cs
  src/Geometry/3D/Primitives/Cylinder.cs
  src/Geometry/3D/Primitives/Sphere.cs
  src/Optimization/KMeansCluster.cs
  tests/Curves/LevelSetsTests.cs
  tests/Geometry/3D/BoxTests.cs
  tests/Geometry/3D/CylinderTests.cs
  tests/Geometry/3D/SphereTests.cs
  tests/Geometry/3D/VectorNd_Tests.cs
  tests/Paramdigma.Core.Tests.csproj
Labels: quality

#17 Simplified some of the code.
  Paramdigma.Core.sln.DotSettings
  src/Geometry/2D/Delaunay.cs
  src/Geometry/2D/DelaunayEdge.cs
  src/Geometry/2D/DelaunayPoint.cs
  src/Geometry/2D/DelaunayTriangle.cs
  tests/Geometry/2D/DelaunayTests.cs
Labels: documentation, enhancement
